M-Code for Time Buckets Column:
------------------------------------------------------------------------------------------------------------------------------------
= Table.AddColumn(#"Reordered Columns", "Time Buckets", each if [Days Open] >= 0 and [Days Open] <= 5 then "0-5 days"
else if [Days Open] >= 6 and [Days Open] <= 10 then "6-10 days"
else if [Days Open] >= 11 and [Days Open] <= 15 then "11-15 days"
else if [Days Open] >= 16 and [Days Open] <= 20 then "16-20 days"
else if [Days Open] >= 21 and [Days Open] <= 25 then "21-25 days"
else if [Days Open] >= 26 and [Days Open] <= 37 then "25+ days"
else "More than 37 days")
------------------------------------------------------------------------------------------------------------------------------------
